include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    experimental_member_use: ignore
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
