import 'package:isar/isar.dart';

part 'accounting_entry.g.dart';

enum TramXangEntryStatus { draft, posted, reversed }

/// Loại nghiệp vụ kế toán của Trạm Xăng (theo TT133 / NĐ 123-2020).
enum TramXangEntryType {
  fuelPurchase,      // Mua xăng dầu nhập kho (Nợ 156 / Có 331+1331)
  fuelSale,          // Bán xăng dầu thu tiền (Nợ 111/131 / Có 511+3331)
  fuelCost,          // Kết chuyển giá vốn (Nợ 632 / Có 156)
  saleReceipt,       // Thu tiền bán hàng
  purchasePayment,   // Chi tiền mua hàng
  customerReceipt,   // Thu nợ khách hàng
  supplierPayment,   // Thanh toán nhà cung cấp
  openingBalance,    // Số dư đầu kỳ
  adjustment,        // Điều chỉnh
  other,             // Nghiệp vụ khác (GLVoucher RefType 4010-4018)
}

/// Bút toán kế toán theo nguyên tắc DR/CR (TT133).
/// Tương ứng GLVoucher trong MISA SME 2023.
@collection
class TramXangAccountingEntry {
  Id id = Isar.autoIncrement;

  /// Số chứng từ (VD: "PN-2026/09-001", "HD-2026/09-001", "GV-2026/09-001").
  @Index(unique: true)
  late String voucherNumber;

  /// Nhóm bút toán (journalID) — tất cả dòng trong 1 bút toán có chung journalID.
  @Index()
  late String journalID;

  late int year;
  late int month;

  /// Loại bút toán.
  @Enumerated(EnumType.name)
  late TramXangEntryType entryType;

  /// Trạng thái (draft → posted → reversed).
  @Enumerated(EnumType.name)
  TramXangEntryStatus status = TramXangEntryStatus.draft;

  /// Ngày ghi sổ (ngày hạch toán).
  late DateTime postingDate;

  /// Ngày lập chứng từ (documentDate).
  late DateTime documentDate;

  /// Ngày ghi sổ kế toán (postedDate — khi bấm "Ghi sổ").
  DateTime? postedDate;

  /// RefType theo MISA (4010=other, 111=cash payment, ...).
  int? refType;

  /// Đơn vị tổ chức.
  String? organizationUnit;

  /// Mô tả nội dung bút toán.
  String? description;

  /// Liên kết đối tượng (khách hàng / NCC / nhân viên).
  String? objectCode;
  String? objectName;

  /// Tổng tiền DR = Tổng tiền CR (phải bằng nhau).
  double totalDebit = 0;
  double totalCredit = 0;

  /// Tiền tệ.
  String? currencyCode = 'VND';
  double exchangeRate = 1.0;

  /// Người lập / người ghi sổ.
  String? createdBy;
  String? postedBy;

  /// Thanh toán.
  String? paymentMethod;    // cash / bank / transfer / debt
  DateTime? paidDate;

  /// Tự động sinh (từ hệ thống POS / kho) hay nhập tay.
  bool isAutoGenerated = false;

  String? notes;

  // Sync
  String? remoteId;
  DateTime? lastSyncAt;
  bool needsSync = false;

  DateTime createdAt = DateTime.now();
  DateTime updatedAt = DateTime.now();
}

/// Chi tiết dòng bút toán (GLVoucherDetail trong MISA).
/// Mỗi dòng = 1 cặp DR/CR account + số tiền + đối tượng.
@collection
class TramXangAccountingEntryLine {
  Id id = Isar.autoIncrement;

  /// Link tới TramXangAccountingEntry qua journalID.
  @Index()
  late String journalID;

  /// Thứ tự dòng.
  late int lineOrder;

  /// Số tài khoản ghi NỢ.
  late String debitAccountNumber;

  /// Số tài khoản ghi CÓ.
  late String creditAccountNumber;

  /// Số tiền.
  late double amount;

  /// Mã đối tượng (khách hàng / NCC).
  String? objectCode;
  String? objectName;

  /// Mô tả dòng bút toán.
  String? description;

  /// Ghi chú dòng.
  String? note;
}