import 'package:isar/isar.dart';

part 'accounting_entry.g.dart';

enum EntryStatus { draft, posted, reversed }
enum EntryType {
  salary,           // Hạch toán lương (PASalaryExpense)
  insurance,        // Hạch toán BHXH/BHYT/BHTN NSDL
  pit,              // Hạch toán thuế TNCN
  payment,          // Chi tiền lương (CAPayment/BAWithDraw)
  advance,          // Tạm ứng
  bonus,            // Thưởng
  adjustment,       // Điều chỉnh
  openingBalance,   // Số dư đầu kỳ
  other,            // Nghiep vu khac (GLVoucher RefType 4010-4018)
}

/// Bút toán kế toán theo nguyên tắc DR/CR (TT133).
/// Tương ứng GLVoucher / PASalaryExpense trong MISA SME 2023.
@collection
class AccountingEntry {
  Id id = Isar.autoIncrement;

  /// Số chứng từ (VD: "GL-2026/08-001", "PC-2026/08-001").
  @Index(unique: true)
  late String voucherNumber;

  /// Nhóm bút toán (journalID) — tất cả dòng trong 1 bút toán có chung journalID.
  @Index()
  late String journalID;

  late int year;
  late int month;

  /// Loại bút toán.
  @Enumerated(EnumType.name)
  late EntryType entryType;

  /// Trạng thái (draft → posted → reversed).
  @Enumerated(EnumType.name)
  EntryStatus status = EntryStatus.draft;

  /// Ngày ghi sổ (ngày hạch toán / RefDate trong MISA).
  late DateTime postingDate;

  /// Ngày lập chứng từ (documentDate).
  late DateTime documentDate;

  /// Ngày ghi sổ kế toán (postedDate — khi bấm "Ghi sổ").
  DateTime? postedDate;

  /// RefType theo MISA (4010=other, 111=cash payment, etc.).
  int? refType;

  /// Đơn vị tổ chức.
  String? organizationUnit;

  /// Mô tả nội dung bút toán.
  String? description;

  /// Liên kết employee (nếu bút toán liên quan lương).
  int? employeeId;
  String? employeeCode;
  String? employeeName;

  /// Tổng tiền DR = Tổng tiền CR (phải bằng nhau).
  double totalDebit = 0;
  double totalCredit = 0;

  /// Tỷ lệ ngoại tệ (nếu có).
  String? currencyCode = 'VND';
  double exchangeRate = 1.0;

  /// Người lập / người duyệt / người ghi sổ.
  String? createdBy;
  String? approvedBy;
  String? postedBy;

  /// Thanh toán.
  String? paymentMethod;    // cash / bank / transfer
  DateTime? paidDate;

  /// Tự động sinh (từ hệ thống lương) hay nhập tay.
  bool isAutoGenerated = false;

  String? notes;

  // Sync
  String? remoteId;
  DateTime? lastSyncAt;
  bool needsSync = false;

  DateTime createdAt = DateTime.now();
  DateTime updatedAt = DateTime.now();
}

/// Chi tiết dòng bút toán (GLVoucherDetail trong MISA).
/// Mỗi dòng = 1 cặp DR/CR account + số tiền + đối tượng.
@collection
class AccountingEntryLine {
  Id id = Isar.autoIncrement;

  /// Link tới AccountingEntry qua journalID.
  @Index()
  late String journalID;

  /// Thứ tự dòng.
  late int lineOrder;

  /// Số tài khoản ghi NỢ.
  late String debitAccountNumber;

  /// Số tài khoản ghi CÓ.
  late String creditAccountNumber;

  /// Số tiền.
  late double amount;

  /// Mã đối tượng (nhân viên / NCC / khách hàng).
  String? objectCode;
  String? objectName;

  /// Mã bộ phận (phòng ban).
  String? departmentCode;

  /// Mã khoản chi phí (expenseItem).
  String? expenseItemCode;

  /// Mã công trình / dự án.
  String? projectCode;

  /// Mã hợp đồng.
  String? contractCode;

  /// Mã công việc (cost object / job).
  String? jobCode;

  /// Mô tả dòng bút toán.
  String? description;

  /// Ghi chú dòng.
  String? note;
}
