import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../core/app_theme.dart';
import '../../core/providers.dart';
import '../../models/accounting_entry.dart';
import '../../models/account.dart';
import '../../models/payroll.dart';
import '../../services/payroll_calculator_service.dart';

/// Màn hình nhập bút toán kế toán GL cho HR Payroll.
/// Hỗ trợ tự động theo loại (lương, BHXH, TNCN, chi tiền, thưởng, tạm ứng)
/// và nhập tay DR/CR theo dòng với đối tượng nhân viên/tài xế.
class GlJournalEntryScreen extends ConsumerStatefulWidget {
  final EntryType initialType;
  final int year;
  final int month;

  const GlJournalEntryScreen({
    super.key,
    this.initialType = EntryType.salary,
    required this.year,
    required this.month,
  });

  @override
  ConsumerState<GlJournalEntryScreen> createState() => _GlJournalEntryScreenState();
}

class _GlJournalEntryScreenState extends ConsumerState<GlJournalEntryScreen> {
  late EntryType _type;
  late int _year;
  late int _month;
  final _descCtrl = TextEditingController();
  String _paymentMethod = 'bank';
  bool _isAutoGen = true;
  final List<_LineData> _lines = [_LineData()];
  bool _saving = false;

  @override
  void initState() {
    super.initState();
    _type = widget.initialType;
    _year = widget.year;
    _month = widget.month;
  }

  @override
  void dispose() {
    _descCtrl.dispose();
    for (final l in _lines) {
      l.dispose();
    }
    super.dispose();
  }

  void _addLine() => setState(() => _lines.add(_LineData()));

  void _removeLine(int i) {
    if (_lines.length <= 1) return;
    setState(() {
      _lines[i].dispose();
      _lines.removeAt(i);
    });
  }

  // ══════════════════ AUTO GENERATE ══════════════════
  Future<void> _autoGenerate() async {
    if (_saving) return;
    setState(() => _saving = true);

    try {
      final db = ref.read(dbProvider);
      final payrolls = await db.getPayrollByMonth(_year, _month);

      if (payrolls.isEmpty && _type != EntryType.advance) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Không có dữ liệu lương tháng này')),
          );
        }
        return;
      }

      AccountingEntry? entry;
      List<AccountingEntryLine> lines = [];

      switch (_type) {
        case EntryType.salary:
          entry = PayrollCalculatorService.buildSalaryJournalEntry(
            year: _year, month: _month, payrolls: payrolls,
          );
          entry.isAutoGenerated = true;
          entry.description = 'Hạch toán lương tháng $_month/$_year (${payrolls.length} người)';
          lines = PayrollCalculatorService.buildSalaryEntryLines(
            journalID: entry.journalID, payrolls: payrolls,
          );
          break;
        case EntryType.insurance:
          entry = _buildInsuranceEntry(payrolls);
          lines = _buildInsuranceLines(entry.journalID, payrolls);
          break;
        case EntryType.pit:
          entry = PayrollCalculatorService.buildPitJournalEntry(
            year: _year, month: _month, payrolls: payrolls,
          );
          entry.isAutoGenerated = true;
          entry.description = 'Khấu trừ thuế TNCN tháng $_month/$_year';
          final totalPit = payrolls.fold<double>(0, (s, p) => s + p.personalIncomeTax);
          lines = [
            AccountingEntryLine()
              ..journalID = entry.journalID
              ..lineOrder = 1
              ..debitAccountNumber = '334'
              ..creditAccountNumber = ''
              ..amount = totalPit
              ..description = 'Dr 334 - Phải trả NLĐ',
            AccountingEntryLine()
              ..journalID = entry.journalID
              ..lineOrder = 2
              ..debitAccountNumber = ''
              ..creditAccountNumber = '3335'
              ..amount = totalPit
              ..description = 'Cr 3335 - Thuế TNCN',
          ];
          break;
        case EntryType.payment:
          entry = PayrollCalculatorService.buildPaymentJournalEntry(
            year: _year, month: _month, payrolls: payrolls, paymentMethod: _paymentMethod,
          );
          entry.isAutoGenerated = true;
          entry.description = 'Chi lương tháng $_month/$_year qua ${_paymentMethod == 'cash' ? 'tiền mặt' : 'NH'}';
          final totalNet = payrolls.fold<double>(0, (s, p) => s + p.netSalary);
          final crAcct = _paymentMethod == 'cash' ? '111' : '112';
          lines = [
            AccountingEntryLine()
              ..journalID = entry.journalID
              ..lineOrder = 1
              ..debitAccountNumber = '334'
              ..creditAccountNumber = ''
              ..amount = totalNet
              ..description = 'Dr 334 - Chi lương NLĐ',
            AccountingEntryLine()
              ..journalID = entry.journalID
              ..lineOrder = 2
              ..debitAccountNumber = ''
              ..creditAccountNumber = crAcct
              ..amount = totalNet
              ..description = 'Cr $crAcct - Tiền gửi NH/tiền mặt',
          ];
          break;
        case EntryType.bonus:
          entry = PayrollCalculatorService.buildBonusJournalEntry(
            year: _year, month: _month, payrolls: payrolls,
          );
          if (entry.voucherNumber.isEmpty) {
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Tháng này không có thưởng')),
              );
            }
            return;
          }
          entry.isAutoGenerated = true;
          final totalBonus = payrolls.fold<double>(0, (s, p) =>
              s + p.safetyBonus + p.fuelSavingBonus + p.kpiBonus + p.monthlyBonus + p.otherBonus);
          lines = [
            AccountingEntryLine()
              ..journalID = entry.journalID
              ..lineOrder = 1
              ..debitAccountNumber = '6422'
              ..creditAccountNumber = ''
              ..amount = totalBonus
              ..description = 'Dr 6422 - Chi phí thưởng',
            AccountingEntryLine()
              ..journalID = entry.journalID
              ..lineOrder = 2
              ..debitAccountNumber = ''
              ..creditAccountNumber = '334'
              ..amount = totalBonus
              ..description = 'Cr 334 - Phải trả NLĐ',
          ];
          break;
        case EntryType.advance:
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Tạm ứng cần nhập tay — chọn Nhập tay DR/CR')),
            );
          }
          return;
        default:
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Loại này cần nhập tay')),
            );
          }
          return;
      }

      await db.saveAccountingEntry(entry);
      await db.saveAccountingEntryLines(lines);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Đã tạo bút toán ${entry.voucherNumber} (${lines.length} dòng)'),
            backgroundColor: AppTheme.success,
          ),
        );
        context.pop();
      }
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  AccountingEntry _buildInsuranceEntry(List<Payroll> payrolls) {
    final totalBhxhEmp = payrolls.fold<double>(0, (s, p) => s + p.employerBhxh);
    final totalBhytEmp = payrolls.fold<double>(0, (s, p) => s + p.employerBhyt);
    final totalBhtnEmp = payrolls.fold<double>(0, (s, p) => s + p.employerBhtn);
    final totalUnion = payrolls.fold<double>(0, (s, p) => s + p.unionFee);
    final total = totalBhxhEmp + totalBhytEmp + totalBhtnEmp + totalUnion;

    final seq = 6;
    final voucherNo = 'GL-${_year.toString().padLeft(4, '0')}/${_month.toString().padLeft(2, '0')}-${seq.toString().padLeft(3, '0')}';
    final journalID = '${PayrollCalculatorService.makeJournalID(_year, _month)}-INS';

    return AccountingEntry()
      ..voucherNumber = voucherNo
      ..journalID = journalID
      ..year = _year
      ..month = _month
      ..entryType = EntryType.insurance
      ..status = EntryStatus.draft
      ..postingDate = DateTime(_year, _month + 1, 5)
      ..documentDate = DateTime.now()
      ..refType = 4010
      ..description = 'Hạch toán BCNLĐ NSDL tháng $_month/$_year'
      ..totalDebit = total
      ..totalCredit = total
      ..isAutoGenerated = true
      ..createdBy = 'System';
  }

  List<AccountingEntryLine> _buildInsuranceLines(String journalID, List<Payroll> payrolls) {
    final totalBhxhEmp = payrolls.fold<double>(0, (s, p) => s + p.employerBhxh);
    final totalBhytEmp = payrolls.fold<double>(0, (s, p) => s + p.employerBhyt);
    final totalBhtnEmp = payrolls.fold<double>(0, (s, p) => s + p.employerBhtn);
    final totalUnion = payrolls.fold<double>(0, (s, p) => s + p.unionFee);

    var n = 0;
    return [
      AccountingEntryLine()
        ..journalID = journalID
        ..lineOrder = ++n
        ..debitAccountNumber = '6422'
        ..creditAccountNumber = ''
        ..amount = totalBhxhEmp + totalBhytEmp + totalBhtnEmp + totalUnion
        ..description = 'Dr 6422 - Chi phí BCNLĐ',
      AccountingEntryLine()
        ..journalID = journalID
        ..lineOrder = ++n
        ..debitAccountNumber = ''
        ..creditAccountNumber = '3383'
        ..amount = totalBhxhEmp
        ..description = 'Cr 3383 - BHXH NSDL',
      AccountingEntryLine()
        ..journalID = journalID
        ..lineOrder = ++n
        ..debitAccountNumber = ''
        ..creditAccountNumber = '3384'
        ..amount = totalBhytEmp
        ..description = 'Cr 3384 - BHYT NSDL',
      AccountingEntryLine()
        ..journalID = journalID
        ..lineOrder = ++n
        ..debitAccountNumber = ''
        ..creditAccountNumber = '3385'
        ..amount = totalBhtnEmp
        ..description = 'Cr 3385 - BHTN NSDL',
      AccountingEntryLine()
        ..journalID = journalID
        ..lineOrder = ++n
        ..debitAccountNumber = ''
        ..creditAccountNumber = '3382'
        ..amount = totalUnion
        ..description = 'Cr 3382 - Kinh phí CĐ',
    ];
  }

  // ══════════════════ MANUAL SAVE ══════════════════
  Future<void> _saveManual() async {
    if (_saving) return;

    final desc = _descCtrl.text.trim();
    if (desc.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Nhập mô tả bút toán')),
      );
      return;
    }

    double totalDr = 0;
    double totalCr = 0;
    for (final l in _lines) {
      if (l.debitAccount.isEmpty || l.amount <= 0) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Mỗi dòng phải có tài khoản Nợ và số tiền > 0')),
        );
        return;
      }
      totalDr += l.amount;
      if (l.creditAccount.isNotEmpty) totalCr += l.amount;
    }
    if ((totalDr - totalCr).abs() > 0.5) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Tổng Nợ phải bằng Tổng Có')),
      );
      return;
    }

    setState(() => _saving = true);
    try {
      final journalID = 'JRN-${_year.toString().padLeft(4, '0')}${_month.toString().padLeft(2, '0')}-MANUAL-${DateTime.now().millisecondsSinceEpoch}';
      final voucherNo = 'GL-${_year.toString().padLeft(4, '0')}/${_month.toString().padLeft(2, '0')}-${DateTime.now().millisecondsSinceEpoch % 1000}';

      final entry = AccountingEntry()
        ..voucherNumber = voucherNo
        ..journalID = journalID
        ..year = _year
        ..month = _month
        ..entryType = _type
        ..status = EntryStatus.draft
        ..postingDate = DateTime(_year, _month, 15)
        ..documentDate = DateTime.now()
        ..refType = 4010
        ..description = desc
        ..totalDebit = totalDr
        ..totalCredit = totalDr
        ..isAutoGenerated = false
        ..createdBy = 'Nhập tay';

      final db = ref.read(dbProvider);
      await db.saveAccountingEntry(entry);

      final entryLines = <AccountingEntryLine>[];
      var order = 0;
      for (final l in _lines) {
        entryLines.add(AccountingEntryLine()
          ..journalID = journalID
          ..lineOrder = ++order
          ..debitAccountNumber = l.debitAccount
          ..creditAccountNumber = l.creditAccount
          ..amount = l.amount
          ..objectCode = l.objectCode.isNotEmpty ? l.objectCode : null
          ..departmentCode = l.deptCode.isNotEmpty ? l.deptCode : null
          ..description = l.desc.isNotEmpty ? l.desc : null
        );
      }
      await db.saveAccountingEntryLines(entryLines);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Đã lưu bút toán nháp $voucherNo'),
            backgroundColor: AppTheme.success,
          ),
        );
        context.pop();
      }
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final accountsAsync = ref.watch(leafAccountsProvider);

    return Scaffold(
      appBar: AppBar(
        title: Text(_typeLabel(_type), style: const TextStyle(color: Colors.white, fontSize: 16)),
        backgroundColor: AppTheme.primaryBlue,
        iconTheme: const IconThemeData(color: Colors.white),
        actions: [
          if (_saving)
            const Padding(
              padding: EdgeInsets.all(16),
              child: SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2)),
            )
          else if (_isAutoGen)
            TextButton.icon(
              onPressed: _autoGenerate,
              icon: const Icon(Icons.auto_awesome, color: Colors.white),
              label: const Text('Tạo tự động', style: TextStyle(color: Colors.white)),
            )
          else
            TextButton.icon(
              onPressed: _saveManual,
              icon: const Icon(Icons.save, color: Colors.white),
              label: const Text('Lưu nháp', style: TextStyle(color: Colors.white)),
            ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Loại bút toán + chế độ
            Row(
              children: [
                Expanded(
                  child: DropdownButtonFormField<EntryType>(
                    value: _type,
                    decoration: const InputDecoration(
                      labelText: 'Loại bút toán',
                      border: OutlineInputBorder(),
                      isDense: true,
                    ),
                    items: const [
                      DropdownMenuItem(value: EntryType.salary, child: Text('Lương (6422/334)')),
                      DropdownMenuItem(value: EntryType.insurance, child: Text('BHXH/BHYT/BHTN')),
                      DropdownMenuItem(value: EntryType.pit, child: Text('Thuế TNCN (334/3335)')),
                      DropdownMenuItem(value: EntryType.payment, child: Text('Chi tiền (334/112)')),
                      DropdownMenuItem(value: EntryType.bonus, child: Text('Thưởng (6422/334)')),
                      DropdownMenuItem(value: EntryType.advance, child: Text('Tạm ứng (141/112)')),
                      DropdownMenuItem(value: EntryType.other, child: Text('Nghiệp vụ khác')),
                    ],
                    onChanged: (v) => setState(() => _type = v!),
                  ),
                ),
                const SizedBox(width: 12),
                Column(
                  children: [
                    Switch(
                      value: _isAutoGen,
                      onChanged: (v) => setState(() => _isAutoGen = v),
                    ),
                    Text(_isAutoGen ? 'Tự động' : 'Nhập tay',
                        style: const TextStyle(fontSize: 11, color: AppTheme.textSecondary)),
                  ],
                ),
              ],
            ),
            const SizedBox(height: 12),

            // Năm / Tháng
            Row(
              children: [
                Expanded(
                  child: DropdownButtonFormField<int>(
                    value: _year,
                    decoration: const InputDecoration(labelText: 'Năm', border: OutlineInputBorder(), isDense: true),
                    items: List.generate(5, (i) => DateTime.now().year - 2 + i)
                        .map((y) => DropdownMenuItem(value: y, child: Text('$y'))).toList(),
                    onChanged: (v) => setState(() => _year = v!),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: DropdownButtonFormField<int>(
                    value: _month,
                    decoration: const InputDecoration(labelText: 'Tháng', border: OutlineInputBorder(), isDense: true),
                    items: List.generate(12, (i) => i + 1)
                        .map((m) => DropdownMenuItem(value: m, child: Text('Tháng $m'))).toList(),
                    onChanged: (v) => setState(() => _month = v!),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),

            // Phương thức thanh toán
            if (_type == EntryType.payment) ...[
              DropdownButtonFormField<String>(
                value: _paymentMethod,
                decoration: const InputDecoration(
                  labelText: 'Phương thức thanh toán',
                  border: OutlineInputBorder(),
                  isDense: true,
                ),
                items: const [
                  DropdownMenuItem(value: 'bank', child: Text('Chuyển khoản (BA-)')),
                  DropdownMenuItem(value: 'cash', child: Text('Tiền mặt (PC-)')),
                ],
                onChanged: (v) => setState(() => _paymentMethod = v!),
              ),
              const SizedBox(height: 12),
            ],

            // Mô tả
            TextField(
              controller: _descCtrl,
              decoration: const InputDecoration(
                labelText: 'Mô tả bút toán',
                border: OutlineInputBorder(),
                hintText: 'VD: Hạch toán lương tháng 8/2026',
              ),
              maxLines: 2,
            ),
            const SizedBox(height: 20),

            // Dòng bút toán
            if (!_isAutoGen) ...[
              Row(
                children: [
                  const Text('Dòng bút toán',
                      style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold, color: AppTheme.textPrimary)),
                  const Spacer(),
                  IconButton(
                    onPressed: _addLine,
                    icon: const Icon(Icons.add_circle, color: AppTheme.primaryBlue),
                    tooltip: 'Thêm dòng',
                  ),
                ],
              ),
              const SizedBox(height: 8),
              ...List.generate(_lines.length, (i) => _lineCard(i, accountsAsync)),
            ],

            // Auto preview
            if (_isAutoGen) ...[
              Card(
                color: AppTheme.surface,
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Icon(_typeIcon(_type), size: 20, color: AppTheme.primaryBlue),
                          const SizedBox(width: 8),
                          Text('Preview: ${_typeLabel(_type)}',
                              style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textPrimary)),
                        ],
                      ),
                      const SizedBox(height: 8),
                      ..._autoPreviewLines(),
                    ],
                  ),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _lineCard(int index, AsyncValue<List<Account>> accountsAsync) {
    final line = _lines[index];
    return Card(
      color: AppTheme.surface,
      margin: const EdgeInsets.only(bottom: 8),
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          children: [
            Row(
              children: [
                Text('Dòng ${index + 1}',
                    style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textPrimary)),
                const Spacer(),
                if (_lines.length > 1)
                  IconButton(
                    onPressed: () => _removeLine(index),
                    icon: const Icon(Icons.delete, color: AppTheme.danger, size: 20),
                    tooltip: 'Xóa dòng',
                  ),
              ],
            ),
            const SizedBox(height: 8),
            accountsAsync.when(
              data: (accounts) => DropdownButtonFormField<String>(
                value: line.debitAccount.isEmpty ? null : line.debitAccount,
                decoration: const InputDecoration(
                  labelText: 'Tài khoản NỢ',
                  border: OutlineInputBorder(),
                  isDense: true,
                ),
                items: accounts.map((a) => DropdownMenuItem(
                  value: a.accountNumber,
                  child: Text('${a.accountNumber} - ${a.accountName}',
                      style: const TextStyle(fontSize: 12)),
                )).toList(),
                onChanged: (v) => setState(() => line.debitAccount = v ?? ''),
              ),
              loading: () => const CircularProgressIndicator(),
              error: (e, _) => Text('Lỗi: $e'),
            ),
            const SizedBox(height: 8),
            accountsAsync.when(
              data: (accounts) => DropdownButtonFormField<String>(
                value: line.creditAccount.isEmpty ? null : line.creditAccount,
                decoration: const InputDecoration(
                  labelText: 'Tài khoản CÓ',
                  border: OutlineInputBorder(),
                  isDense: true,
                ),
                items: accounts.map((a) => DropdownMenuItem(
                  value: a.accountNumber,
                  child: Text('${a.accountNumber} - ${a.accountName}',
                      style: const TextStyle(fontSize: 12)),
                )).toList(),
                onChanged: (v) => setState(() => line.creditAccount = v ?? ''),
              ),
              loading: () => const CircularProgressIndicator(),
              error: (e, _) => Text('Lỗi: $e'),
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  flex: 2,
                  child: TextField(
                    controller: line.amountCtrl,
                    keyboardType: TextInputType.number,
                    decoration: const InputDecoration(
                      labelText: 'Số tiền',
                      border: OutlineInputBorder(),
                      isDense: true,
                    ),
                    onChanged: (v) => line.amount = double.tryParse(v) ?? 0,
                  ),
                ),
                const SizedBox(width: 8),
                Expanded(
                  flex: 2,
                  child: TextField(
                    controller: line.objectCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Đối tượng (NV/TX)',
                      border: OutlineInputBorder(),
                      isDense: true,
                      hintText: 'Mã NV',
                    ),
                    onChanged: (v) => line.objectCode = v,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: line.deptCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Bộ phận',
                      border: OutlineInputBorder(),
                      isDense: true,
                    ),
                    onChanged: (v) => line.deptCode = v,
                  ),
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: TextField(
                    controller: line.descCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Ghi chú dòng',
                      border: OutlineInputBorder(),
                      isDense: true,
                    ),
                    onChanged: (v) => line.desc = v,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  List<Widget> _autoPreviewLines() {
    switch (_type) {
      case EntryType.salary:
        return [
          _previewRow('Dr', '6422', 'Chi phí lương + BCNLĐ', AppTheme.danger),
          _previewRow('Cr', '334', 'Phải trả NLĐ', AppTheme.accent),
          _previewRow('Cr', '3383', 'BHXH NSDL', AppTheme.accent),
          _previewRow('Cr', '3384', 'BHYT NSDL', AppTheme.accent),
          _previewRow('Cr', '3385', 'BHTN NSDL', AppTheme.accent),
          _previewRow('Cr', '3382', 'Kinh phí CĐ', AppTheme.accent),
        ];
      case EntryType.insurance:
        return [
          _previewRow('Dr', '6422', 'Chi phí BCNLĐ NSDL', AppTheme.danger),
          _previewRow('Cr', '3383', 'BHXH phần NSDL', AppTheme.accent),
          _previewRow('Cr', '3384', 'BHYT phần NSDL', AppTheme.accent),
          _previewRow('Cr', '3385', 'BHTN phần NSDL', AppTheme.accent),
          _previewRow('Cr', '3382', 'Kinh phí CĐ 2%', AppTheme.accent),
        ];
      case EntryType.pit:
        return [
          _previewRow('Dr', '334', 'Phải trả NLĐ (khấu trừ)', AppTheme.danger),
          _previewRow('Cr', '3335', 'Thuế TNCN', AppTheme.accent),
        ];
      case EntryType.payment:
        final crAcct = _paymentMethod == 'cash' ? '111' : '112';
        final crName = _paymentMethod == 'cash' ? 'Tiền mặt' : 'Tiền gửi NH';
        return [
          _previewRow('Dr', '334', 'Chi lương NLĐ', AppTheme.danger),
          _previewRow('Cr', crAcct, crName, AppTheme.accent),
        ];
      case EntryType.bonus:
        return [
          _previewRow('Dr', '6422', 'Chi phí thưởng', AppTheme.danger),
          _previewRow('Cr', '334', 'Phải trả NLĐ', AppTheme.accent),
        ];
      case EntryType.advance:
        return [
          _previewRow('Dr', '141', 'Tạm ứng', AppTheme.danger),
          _previewRow('Cr', '112', 'Tiền gửi NH', AppTheme.accent),
        ];
      default:
        return [
          const Text('Chọn loại để xem trước cấu trúc hạch toán',
              style: TextStyle(fontSize: 12, color: AppTheme.textSecondary)),
        ];
    }
  }

  static Widget _previewRow(String side, String account, String desc, Color color) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(
        children: [
          SizedBox(
            width: 24,
            child: Text(side,
                style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: color)),
          ),
          const SizedBox(width: 8),
          SizedBox(
            width: 50,
            child: Text(account, style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: color)),
          ),
          Expanded(
            child: Text(desc, style: const TextStyle(fontSize: 12, color: AppTheme.textSecondary)),
          ),
        ],
      ),
    );
  }

  static IconData _typeIcon(EntryType type) {
    switch (type) {
      case EntryType.salary: return Icons.account_balance_wallet;
      case EntryType.insurance: return Icons.health_and_safety;
      case EntryType.pit: return Icons.receipt;
      case EntryType.payment: return Icons.payments;
      case EntryType.advance: return Icons.money;
      case EntryType.bonus: return Icons.card_giftcard;
      case EntryType.adjustment: return Icons.tune;
      case EntryType.openingBalance: return Icons.account_balance_wallet_outlined;
      case EntryType.other: return Icons.receipt_long;
    }
  }

  static String _typeLabel(EntryType t) {
    switch (t) {
      case EntryType.salary: return 'Lương (Dr 6422 / Cr 334+338x)';
      case EntryType.insurance: return 'BHXH/BHYT/BHTN (Dr 6422 / Cr 338x)';
      case EntryType.pit: return 'Thuế TNCN (Dr 334 / Cr 3335)';
      case EntryType.payment: return 'Chi tiền (Dr 334 / Cr 112)';
      case EntryType.advance: return 'Tạm ứng (Dr 141 / Cr 112)';
      case EntryType.bonus: return 'Thưởng (Dr 6422 / Cr 334)';
      case EntryType.adjustment: return 'Điều chỉnh';
      case EntryType.openingBalance: return 'Số dư đầu kỳ';
      case EntryType.other: return 'Nghiệp vụ khác';
    }
  }
}

class _LineData {
  String debitAccount = '';
  String creditAccount = '';
  double amount = 0;
  String objectCode = '';
  String deptCode = '';
  String desc = '';
  final TextEditingController amountCtrl = TextEditingController();
  final TextEditingController objectCtrl = TextEditingController();
  final TextEditingController deptCtrl = TextEditingController();
  final TextEditingController descCtrl = TextEditingController();

  void dispose() {
    amountCtrl.dispose();
    objectCtrl.dispose();
    deptCtrl.dispose();
    descCtrl.dispose();
  }
}
