import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../core/app_theme.dart';
import '../../core/providers.dart';
import '../../models/accounting_entry.dart';
import '../../models/account.dart';
import '../../services/payroll_calculator_service.dart';

/// Screen nhập bút toán kế toán — tương ứng GLVoucher / CAPayment / BAWithDraw
/// trong MISA SME 2023.
/// Hỗ trợ: nhập tay, tự động theo loại (lương, BHXH, TNCN, chi tiền).
class JournalEntryInputScreen extends ConsumerStatefulWidget {
  const JournalEntryInputScreen({super.key});

  @override
  ConsumerState<JournalEntryInputScreen> createState() => _JournalEntryInputScreenState();
}

class _JournalEntryInputScreenState extends ConsumerState<JournalEntryInputScreen> {
  EntryType _selectedType = EntryType.salary;
  int _year = DateTime.now().year;
  int _month = DateTime.now().month;
  final _descCtrl = TextEditingController();
  String _paymentMethod = 'bank';
  bool _isAutoGen = false;
  final List<_LineData> _lines = [_LineData()];

  @override
  void dispose() {
    _descCtrl.dispose();
    super.dispose();
  }

  void _addLine() => setState(() => _lines.add(_LineData()));

  void _removeLine(int i) {
    if (_lines.length <= 1) return;
    setState(() => _lines.removeAt(i));
  }

  /// Tự động sinh bút toán theo loại (lương, TNCN, chi tiền, tạm ứng).
  void _autoGenerate() async {
    final db = ref.read(dbProvider);
    final payrolls = await db.getPayrollByMonth(_year, _month);
    if (payrolls.isEmpty && _selectedType != EntryType.advance) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Không có dữ liệu lương tháng này')),
        );
      }
      return;
    }

    AccountingEntry? entry;
    List<AccountingEntryLine> lines = [];

    switch (_selectedType) {
      case EntryType.salary:
        entry = PayrollCalculatorService.buildSalaryJournalEntry(
          year: _year, month: _month, payrolls: payrolls,
        );
        entry.isAutoGenerated = true;
        entry.description = 'Hạch toán lương tháng $_month/$_year (tự động)';
        lines = PayrollCalculatorService.buildSalaryEntryLines(
          journalID: entry.journalID, payrolls: payrolls,
        );
        break;
      case EntryType.pit:
        entry = PayrollCalculatorService.buildPitJournalEntry(
          year: _year, month: _month, payrolls: payrolls,
        );
        entry.isAutoGenerated = true;
        entry.description = 'TNCN tháng $_month/$_year (tự động)';
        final totalPit = payrolls.fold<double>(0, (s, p) => s + p.personalIncomeTax);
        lines = [
          AccountingEntryLine()
            ..journalID = entry.journalID
            ..lineOrder = 1
            ..debitAccountNumber = '334'
            ..creditAccountNumber = ''
            ..amount = totalPit
            ..description = 'Dr 334 - Phải trả NLĐ',
          AccountingEntryLine()
            ..journalID = entry.journalID
            ..lineOrder = 2
            ..debitAccountNumber = ''
            ..creditAccountNumber = '3335'
            ..amount = totalPit
            ..description = 'Cr 3335 - Thuế TNCN',
        ];
        break;
      case EntryType.payment:
        entry = PayrollCalculatorService.buildPaymentJournalEntry(
          year: _year, month: _month, payrolls: payrolls, paymentMethod: _paymentMethod,
        );
        entry.isAutoGenerated = true;
        entry.description = 'Chi lương tháng $_month/$_year (tự động)';
        final totalNet = payrolls.fold<double>(0, (s, p) => s + p.netSalary);
        final crAccount = _paymentMethod == 'cash' ? '111' : '112';
        lines = [
          AccountingEntryLine()
            ..journalID = entry.journalID
            ..lineOrder = 1
            ..debitAccountNumber = '334'
            ..creditAccountNumber = ''
            ..amount = totalNet
            ..description = 'Dr 334 - Chi lương NLĐ',
          AccountingEntryLine()
            ..journalID = entry.journalID
            ..lineOrder = 2
            ..debitAccountNumber = ''
            ..creditAccountNumber = crAccount
            ..amount = totalNet
            ..description = 'Cr $crAccount - Tiền gửi NH/tiền mặt',
        ];
        break;
      case EntryType.bonus:
        entry = PayrollCalculatorService.buildBonusJournalEntry(
          year: _year, month: _month, payrolls: payrolls,
        );
        if (entry.voucherNumber.isEmpty) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Tháng này không có thưởng')),
            );
          }
          return;
        }
        entry.isAutoGenerated = true;
        final totalBonus = payrolls.fold<double>(0, (s, p) =>
            s + p.safetyBonus + p.fuelSavingBonus + p.kpiBonus + p.monthlyBonus + p.otherBonus);
        lines = [
          AccountingEntryLine()
            ..journalID = entry.journalID
            ..lineOrder = 1
            ..debitAccountNumber = '6422'
            ..creditAccountNumber = ''
            ..amount = totalBonus
            ..description = 'Dr 6422 - Chi phí thưởng',
          AccountingEntryLine()
            ..journalID = entry.journalID
            ..lineOrder = 2
            ..debitAccountNumber = ''
            ..creditAccountNumber = '334'
            ..amount = totalBonus
            ..description = 'Cr 334 - Phải trả NLĐ',
        ];
        break;
      default:
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Loại này không hỗ trợ tự động')),
          );
        }
        return;
    }

    // Save to DB
    await db.saveAccountingEntry(entry);
    await db.saveAccountingEntryLines(lines);

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Đã tạo bút toán ${entry.voucherNumber} + ${lines.length} dòng'),
          backgroundColor: AppTheme.success,
        ),
      );
      context.pop();
    }
  }

  /// Lưu bút toán nhập tay.
  void _saveManual() async {
    final desc = _descCtrl.text.trim();
    if (desc.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Nhập mô tả bút toán')),
      );
      return;
    }

    // Validate DR/CR
    double totalDr = 0;
    double totalCr = 0;
    for (final l in _lines) {
      if (l.debitAccount.isEmpty || l.amount <= 0) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Mỗi dòng phải có tài khoản Nợ và số tiền > 0')),
        );
        return;
      }
      totalDr += l.amount;
      if (l.creditAccount.isNotEmpty) totalCr += l.amount;
    }
    if ((totalDr - totalCr).abs() > 0.5) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Tổng Nợ phải bằng Tổng Có')),
      );
      return;
    }

    final journalID = 'JRN-${_year.toString().padLeft(4, '0')}${_month.toString().padLeft(2, '0')}-MANUAL-${DateTime.now().millisecondsSinceEpoch}';
    final voucherNo = 'GL-${_year.toString().padLeft(4, '0')}/${_month.toString().padLeft(2, '0')}-${DateTime.now().millisecondsSinceEpoch % 1000}';

    final entry = AccountingEntry()
      ..voucherNumber = voucherNo
      ..journalID = journalID
      ..year = _year
      ..month = _month
      ..entryType = _selectedType
      ..status = EntryStatus.draft
      ..postingDate = DateTime(_year, _month, 15)
      ..documentDate = DateTime.now()
      ..refType = 4010
      ..description = desc
      ..totalDebit = totalDr
      ..totalCredit = totalDr
      ..isAutoGenerated = false
      ..createdBy = 'Nhập tay';

    final db = ref.read(dbProvider);
    await db.saveAccountingEntry(entry);

    final entryLines = <AccountingEntryLine>[];
    var order = 0;
    for (final l in _lines) {
      entryLines.add(AccountingEntryLine()
        ..journalID = journalID
        ..lineOrder = ++order
        ..debitAccountNumber = l.debitAccount
        ..creditAccountNumber = l.creditAccount
        ..amount = l.amount
        ..objectCode = l.objectCode.isNotEmpty ? l.objectCode : null
        ..departmentCode = l.deptCode.isNotEmpty ? l.deptCode : null
        ..description = l.desc.isNotEmpty ? l.desc : null
      );
    }
    await db.saveAccountingEntryLines(entryLines);

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Đã lưu bút toán nháp $voucherNo'),
          backgroundColor: AppTheme.success,
        ),
      );
      context.pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    final accountsAsync = ref.watch(leafAccountsProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Nhập bút toán kế toán', style: TextStyle(color: Colors.white)),
        backgroundColor: AppTheme.primaryBlue,
        iconTheme: const IconThemeData(color: Colors.white),
        actions: [
          if (_isAutoGen)
            TextButton.icon(
              onPressed: _autoGenerate,
              icon: const Icon(Icons.auto_awesome, color: Colors.white),
              label: const Text('Tạo tự động', style: TextStyle(color: Colors.white)),
            )
          else
            TextButton.icon(
              onPressed: _saveManual,
              icon: const Icon(Icons.save, color: Colors.white),
              label: const Text('Lưu nháp', style: TextStyle(color: Colors.white)),
            ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ── Loại bút toán + Tự động ──
            Row(
              children: [
                Expanded(
                  child: DropdownButtonFormField<EntryType>(
                    value: _selectedType,
                    decoration: const InputDecoration(
                      labelText: 'Loại bút toán',
                      border: OutlineInputBorder(),
                    ),
                    items: EntryType.values.map((t) => DropdownMenuItem(
                      value: t,
                      child: Text(_typeLabel(t), style: const TextStyle(fontSize: 13)),
                    )).toList(),
                    onChanged: (v) => setState(() => _selectedType = v!),
                  ),
                ),
                const SizedBox(width: 12),
                Switch(
                  value: _isAutoGen,
                  onChanged: (v) => setState(() => _isAutoGen = v),
                ),
                Text(_isAutoGen ? 'Tự động' : 'Nhập tay',
                    style: const TextStyle(fontSize: 12, color: AppTheme.textSecondary)),
              ],
            ),
            const SizedBox(height: 12),

            // ── Năm / Tháng ──
            Row(
              children: [
                Expanded(
                  child: DropdownButtonFormField<int>(
                    value: _year,
                    decoration: const InputDecoration(labelText: 'Năm', border: OutlineInputBorder()),
                    items: List.generate(5, (i) => DateTime.now().year - 2 + i)
                        .map((y) => DropdownMenuItem(value: y, child: Text('$y'))).toList(),
                    onChanged: (v) => setState(() => _year = v!),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: DropdownButtonFormField<int>(
                    value: _month,
                    decoration: const InputDecoration(labelText: 'Tháng', border: OutlineInputBorder()),
                    items: List.generate(12, (i) => i + 1)
                        .map((m) => DropdownMenuItem(value: m, child: Text('Tháng $m'))).toList(),
                    onChanged: (v) => setState(() => _month = v!),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),

            // ── Phương thức thanh toán (nếu là chi tiền) ──
            if (_selectedType == EntryType.payment) ...[
              DropdownButtonFormField<String>(
                value: _paymentMethod,
                decoration: const InputDecoration(
                  labelText: 'Phương thức thanh toán',
                  border: OutlineInputBorder(),
                ),
                items: const [
                  DropdownMenuItem(value: 'bank', child: Text('Chuyển khoản')),
                  DropdownMenuItem(value: 'cash', child: Text('Tiền mặt')),
                ],
                onChanged: (v) => setState(() => _paymentMethod = v!),
              ),
              const SizedBox(height: 12),
            ],

            // ── Mô tả ──
            TextField(
              controller: _descCtrl,
              decoration: const InputDecoration(
                labelText: 'Mô tả bút toán',
                border: OutlineInputBorder(),
                hintText: 'VD: Hạch toán lương tháng 8/2026',
              ),
              maxLines: 2,
            ),
            const SizedBox(height: 20),

            // ── Dòng bút toán ──
            Row(
              children: [
                const Text('Dòng bút toán',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: AppTheme.textPrimary)),
                const Spacer(),
                if (!_isAutoGen)
                  IconButton(
                    onPressed: _addLine,
                    icon: const Icon(Icons.add_circle, color: AppTheme.primaryBlue),
                    tooltip: 'Thêm dòng',
                  ),
              ],
            ),
            const SizedBox(height: 8),

            ...List.generate(_lines.length, (i) => _lineCard(i, accountsAsync)),
          ],
        ),
      ),
    );
  }

  Widget _lineCard(int index, AsyncValue<List<Account>> accountsAsync) {
    final line = _lines[index];
    return Card(
      color: AppTheme.surface,
      margin: const EdgeInsets.only(bottom: 8),
      child: Padding(
        padding: const EdgeInsets.all(12),
        child: Column(
          children: [
            Row(
              children: [
                Text('Dòng ${index + 1}',
                    style: const TextStyle(fontWeight: FontWeight.bold, color: AppTheme.textPrimary)),
                const Spacer(),
                if (_lines.length > 1 && !_isAutoGen)
                  IconButton(
                    onPressed: () => _removeLine(index),
                    icon: const Icon(Icons.delete, color: AppTheme.danger, size: 20),
                    tooltip: 'Xóa dòng',
                  ),
              ],
            ),
            const SizedBox(height: 8),
            // Tài khoản Nợ
            accountsAsync.when(
              data: (accounts) => DropdownButtonFormField<String>(
                value: line.debitAccount.isEmpty ? null : line.debitAccount,
                decoration: const InputDecoration(
                  labelText: 'Tài khoản NỢ',
                  border: OutlineInputBorder(),
                  isDense: true,
                ),
                items: accounts.map((a) => DropdownMenuItem(
                  value: a.accountNumber,
                  child: Text('${a.accountNumber} - ${a.accountName}',
                      style: const TextStyle(fontSize: 12)),
                )).toList(),
                onChanged: (v) => setState(() => line.debitAccount = v ?? ''),
              ),
              loading: () => const CircularProgressIndicator(),
              error: (e, _) => Text('Lỗi: $e'),
            ),
            const SizedBox(height: 8),
            // Tài khoản Có
            accountsAsync.when(
              data: (accounts) => DropdownButtonFormField<String>(
                value: line.creditAccount.isEmpty ? null : line.creditAccount,
                decoration: const InputDecoration(
                  labelText: 'Tài khoản CÓ',
                  border: OutlineInputBorder(),
                  isDense: true,
                ),
                items: accounts.map((a) => DropdownMenuItem(
                  value: a.accountNumber,
                  child: Text('${a.accountNumber} - ${a.accountName}',
                      style: const TextStyle(fontSize: 12)),
                )).toList(),
                onChanged: (v) => setState(() => line.creditAccount = v ?? ''),
              ),
              loading: () => const CircularProgressIndicator(),
              error: (e, _) => Text('Lỗi: $e'),
            ),
            const SizedBox(height: 8),
            // Số tiền + Đối tượng
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: line.amountCtrl,
                    keyboardType: TextInputType.number,
                    decoration: const InputDecoration(
                      labelText: 'Số tiền',
                      border: OutlineInputBorder(),
                      isDense: true,
                    ),
                    onChanged: (v) => line.amount = double.tryParse(v) ?? 0,
                  ),
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: TextField(
                    controller: line.objectCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Đối tượng',
                      border: OutlineInputBorder(),
                      isDense: true,
                    ),
                    onChanged: (v) => line.objectCode = v,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: line.deptCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Bộ phận',
                      border: OutlineInputBorder(),
                      isDense: true,
                    ),
                    onChanged: (v) => line.deptCode = v,
                  ),
                ),
                const SizedBox(width: 8),
                Expanded(
                  child: TextField(
                    controller: line.descCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Ghi chú dòng',
                      border: OutlineInputBorder(),
                      isDense: true,
                    ),
                    onChanged: (v) => line.desc = v,
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  static String _typeLabel(EntryType t) {
    switch (t) {
      case EntryType.salary: return 'Lương (PASalaryExpense)';
      case EntryType.insurance: return 'BHXH/BHYT/BHTN';
      case EntryType.pit: return 'Thuế TNCN';
      case EntryType.payment: return 'Chi tiền (CAPayment/BAWithDraw)';
      case EntryType.advance: return 'Tạm ứng (GLVoucher 141)';
      case EntryType.bonus: return 'Thưởng (GLVoucher)';
      case EntryType.adjustment: return 'Điều chỉnh';
      case EntryType.openingBalance: return 'Số dư đầu kỳ';
      case EntryType.other: return 'Nghiệp vụ khác';
    }
  }
}

/// Data class cho 1 dòng bút toán nhập tay.
class _LineData {
  String debitAccount = '';
  String creditAccount = '';
  double amount = 0;
  String objectCode = '';
  String deptCode = '';
  String desc = '';
  final TextEditingController amountCtrl = TextEditingController();
  final TextEditingController objectCtrl = TextEditingController();
  final TextEditingController deptCtrl = TextEditingController();
  final TextEditingController descCtrl = TextEditingController();
}
